name: Python CI
on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::518773205675:role/libra-base-githubactions-role
          aws-region: ap-northeast-1

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        working-directory: backend/libra-api
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Ëá¥ÂëΩÁöÑ„Å™„Ç®„É©„Éº„ÄÇworkflow„ÇíÊ≠¢„ÇÅ„Åæ„Åô„ÄÇ
      - name: Lint with flake8(Error)
        id: lint-err
        working-directory: backend/libra-api
        run: pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#
      # Ë≠¶Âëä„ÄÇworkflow„ÅØÊ≠¢„ÇÅ„Åæ„Åõ„Çì„ÄÇ(GitHub „Ç®„Éá„Ç£„Çø„ÅÆÂπÖ„ÅØ 127 ÊñáÂ≠ó)
      - name: Lint with flake8(Warning)
        id: lint-war
        working-directory: backend/libra-api
        continue-on-error: true
        #run: pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        run: pipenv run flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        id: test
        working-directory: backend/libra-api/tests
        continue-on-error: true
        run: pipenv run pytest -s -v --cov

      - name: Update Pull Request
        uses: actions/github-script@v6
        env:
          LINT-ERR: "flake8-Error\n${{ steps.lint-err.outputs.stdout }}"
          LINT-WAR: "flake8-Warning\n${{ steps.lint-war.outputs.stdout }}"
          TEST: "pytest\n${{ steps.test.outputs.stdout }}"
        with:
          script: |
            const output = `## \`backend/libra-api\`
            #### Python Lint Error üñå\`${{ steps.lint-err.outcome }}\`
            #### Python Lint Warning üñå\`${{ steps.lint-war.outcome }}\`
            #### Python Test ‚öôÔ∏è\`${{ steps.test.outcome }}\`

            <details><summary>Show Result</summary>

            \`\`\`\n
            ${process.env.LINT-ERR}
            ${process.env.LINT-WAR}
            \`\`\`

            \`\`\`\n
            ${process.env.TEST}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })